services:
  # A Docker web service
  - type: web
    name: webdis-cors
    env: docker
    repo: https://github.com/zuhaz/cors-anywhere.git
    plan: free
    branch: master
    envVars:
      - key: PORT
        value: 3000
